### ISSUE TITLE
Autoscaling support breaks module upgrades

### ISSUE THREAD

**Issue by bodgit** [spacelift-io/terraform-aws-spacelift-workerpool-on-ec2#52]
Version 1.7.0 adding the autoscaling support; I don't particularly want or need that so I added `enable_autoscaling = false` to disable it. However the three new `spacelift_api_key_*` variables are marked as required, so I now have to set them regardless.

Also, it might have been better to default the autoscaling support to `false` rather than `true`.

**Comment by bodgit** [comment]
I've ended up having to add the following to get my Dependabot-raised module update to pass as a no-op:
```hcl
  enable_autoscaling         = false
  spacelift_api_key_id       = ""
  spacelift_api_key_secret   = ""
  spacelift_api_key_endpoint = ""
```

**Comment by eminalemdar** [comment]
Hello @bodgit, thank you for creating this issue. 

The `spacelift_api_key_*` variables are nullable. So you can pass `null` as default values to those variables.

**Comment by bodgit** [comment]
The point was I've had to set them to _something_ as a consumer of the module, even though I'm not making use of them, which isn't great module design.

Ideally the module should declare default values for them; `null` or `""` however you see fit, and then within the module could have some logic similar to:
```hcl
count = var.enable_autoscaling && var.spacelift_api_key_id != "" && ... ? 1 : 0
```
...and by defaulting the autoscaling boolean to `false` upgrading to new versions of the module follow the path of least surprise.

**Comment by jmfontaine** [comment]
Hi @bodgit.

I agree with you. Requiring values for variables that you do not need is a bad user experience. We will fix that, but I think that most people want the ASG to auto-scale, so we will probably keep using `true` as the default value for the `enable_autoscaling` variable.

Thanks a lot for the feedback!

**Comment by bodgit** [comment]
Confirmed fixed. Thanks for the update.
