### ISSUE TITLE
Providers is using a super old version of AWS

### ISSUE THREAD

**Issue by Maelstromeous** [spacelift-io/terraform-aws-spacelift-workerpool-on-ec2#90]
Hello!

Your provider config is using v4 of the AWS hashicorp library. This is regarded as super old and obsolute.

I have an issue now that since I'm using a modern version of the provider (v5.53), I now cannot use your module because your version is too old. Please update it :)

**Comment by Maelstromeous** [comment]
![image](https://github.com/spacelift-io/terraform-aws-spacelift-workerpool-on-ec2/assets/1776058/5abecd07-6799-42ad-bce4-ccac054b02d8)

**Comment by lorengordon** [comment]
Hi @Maelstromeous, that output is attempting to show you that _your own_ config is pinned to 4.0, using `~> 4.0`. That syntax means "any version greater than 4.0, but less than 5.0". It's easy to misinterpret the tree-style output, but that line is representing the version restriction in your own config, not this module.

The output shows that this module is using `>= 4.0.0`, which means "any version greater than 4.0.0, with no restriction on the upper bound". So this module is not actually "using" v4 at all, it's just saying that is the _minimum_ version supported.

**Comment by Apollorion** [comment]
Thanks @lorengordon, this is correct. @Maelstromeous I would recommend upgrading your providers in your hcl lock file via the `-upgrade` command flag. You can see how to do that [here](https://developer.hashicorp.com/terraform/tutorials/configuration-language/provider-versioning#upgrade-the-aws-provider-version). :)

**Comment by Maelstromeous** [comment]
I always forget the .lock file! Thanks guys, long day it was! :P
